# Generated by Django 3.1.7 on 2021-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gdp',
            field=models.BigIntegerField(),
        ),
    ]
