# Generated by Django 3.1.7 on 2021-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210401_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='global_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='local_score',
            field=models.IntegerField(default=0),
        ),
    ]
