# Generated by Django 3.1.7 on 2021-06-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_auto_20210613_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleWordQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(blank=True, max_length=128, null=True)),
                ('ques_image', models.URLField(blank=True, null=True)),
                ('answer', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SingleWordQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(default=0)),
                ('quiz_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modes.singlewordquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userinfo')),
            ],
        ),
    ]
