# Generated by Django 3.1.7 on 2021-06-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210613_1806'),
        ('modes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_text', models.CharField(max_length=128)),
                ('option1', models.CharField(max_length=56)),
                ('option2', models.CharField(max_length=56)),
                ('option3', models.CharField(max_length=56)),
                ('option4', models.CharField(max_length=56)),
                ('answer', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(default=0)),
                ('quiz_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modes.multiplequiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userinfo')),
            ],
        ),
    ]
