# Generated by Django 3.1.7 on 2021-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0002_multiplequiz_multiplequizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=128)),
            ],
        ),
    ]
