# Generated by Django 3.1.7 on 2021-06-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210613_1806'),
        ('modes', '0003_chanbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleClickerIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=56)),
                ('sector', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('industry_number', models.IntegerField(default=0)),
                ('manager_name', models.CharField(max_length=56)),
                ('manager_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdleClickerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('current_quantity', models.IntegerField(default=0)),
                ('last_buy_time', models.DateTimeField()),
                ('quantity_bought', models.IntegerField()),
                ('industry_income', models.BigIntegerField()),
                ('managed', models.BooleanField(default=False)),
                ('next_one_buy', models.BigIntegerField()),
                ('next_ten_buy', models.BigIntegerField()),
                ('next_hundred_buy', models.BigIntegerField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modes.idleclickerindustry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userinfo')),
            ],
        ),
    ]
