# Generated by Django 3.1.7 on 2021-06-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210613_1806'),
        ('modes', '0004_idleclickerindustry_idleclickerparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialModeIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('sector', models.IntegerField(default=0)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('alert', models.CharField(blank=True, max_length=56, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='idleclickerindustry',
            name='unit_industry_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='last_buy_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SpecialModeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.IntegerField(default=1)),
                ('slider2', models.IntegerField(default=1)),
                ('slider3', models.IntegerField(default=1)),
                ('slider4', models.IntegerField(default=1)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modes.specialmodeindustry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userinfo')),
            ],
        ),
    ]
