# Generated by Django 3.1.7 on 2021-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0005_auto_20210620_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodeindustry',
            name='front_end_id',
            field=models.IntegerField(default=0),
        ),
    ]
