# Generated by Django 3.1.7 on 2021-06-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0006_specialmodeindustry_front_end_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='industry_income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='next_hundred_buy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='next_one_buy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='next_ten_buy',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idleclickerparameter',
            name='quantity_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialmodeparameter',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='modes.specialmodeindustry'),
        ),
    ]
