# Generated by Django 3.1.7 on 2021-06-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modes', '0008_auto_20210622_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmodeindustry',
            name='weightage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
